import { auth, db } from "./firebase.js";

import {
doc,
getDoc,
setDoc
} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

import {
onAuthStateChanged
} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";

// ===============================
// MISSION 14 CONFIGURATION
// ===============================

const category = "softwareDevelopment";
const questionNumber = 14;
const questionId = "softwareDevelopment_q14";

// ===============================
// SCORE SYSTEM
// ===============================

const scores = {

blueRoom: 3,

greenRoom: 1,

redRoom: 5

};

// ===============================
// HTML ELEMENTS
// ===============================

const doors = document.querySelectorAll(".door");

const nextBtn = document.getElementById("nextBtn");

const statusText = document.getElementById("statusText");

const progressFill = document.querySelector(".fill");

// ===============================
// STATE
// ===============================

let currentUser = null;

let selectedAnswer = null;

let selectedScore = 0;

let answerLocked = false;

let answerSaved = false;

// ===============================
// INITIAL STATE
// ===============================

nextBtn.disabled = true;

// ===============================
// CHECK PREVIOUS ANSWER
// ===============================

async function checkPreviousAnswer() {

if (!currentUser) return;

try {

    const missionRef = doc(
            db,
                    "users",
                            currentUser.uid,
                                    "missions",
                                            questionId
                                                );

                                                    const missionSnap = await getDoc(missionRef);


                                                        if (missionSnap.exists()) {

                                                                const data = missionSnap.data();

                                                                        selectedAnswer = data.answer;

                                                                                selectedScore = data.score || 0;

                                                                                        answerLocked = true;

                                                                                                answerSaved = true;


                                                                                                        doors.forEach(door => {

                                                                                                                    if (
                                                                                                                                    door.dataset.answer ===
                                                                                                                                                    selectedAnswer
                                                                                                                                                                ) {

                                                                                                                                                                                door.classList.add("selected");

                                                                                                                                                                                            } else {

                                                                                                                                                                                                            door.style.opacity = "0.5";

                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                });


                                                                                                                                                                                                                                        progressFill.style.width =
                                                                                                                                                                                                                                                    "100%";


                                                                                                                                                                                                                                                            statusText.textContent =
                                                                                                                                                                                                                                                                        "✅ Your answer was already saved.";


                                                                                                                                                                                                                                                                                nextBtn.disabled = false;

                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                    } catch (error) {

                                                                                                                                                                                                                                                                                        console.error(
                                                                                                                                                                                                                                                                                                "Error checking previous answer:",
                                                                                                                                                                                                                                                                                                        error
                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                            // ===============================
                                                                                                                                                                                                                                                                                                            // SAVE ANSWER
                                                                                                                                                                                                                                                                                                            // ===============================

                                                                                                                                                                                                                                                                                                            async function saveAnswer() {

                                                                                                                                                                                                                                                                                                            if (!currentUser || !selectedAnswer) {

                                                                                                                                                                                                                                                                                                                return false;

                                                                                                                                                                                                                                                                                                                }


                                                                                                                                                                                                                                                                                                                try {

                                                                                                                                                                                                                                                                                                                    const missionRef = doc(

                                                                                                                                                                                                                                                                                                                            db,

                                                                                                                                                                                                                                                                                                                                    "users",

                                                                                                                                                                                                                                                                                                                                            currentUser.uid,

                                                                                                                                                                                                                                                                                                                                                    "missions",

                                                                                                                                                                                                                                                                                                                                                            questionId

                                                                                                                                                                                                                                                                                                                                                                );


                                                                                                                                                                                                                                                                                                                                                                    await setDoc(

                                                                                                                                                                                                                                                                                                                                                                            missionRef,

                                                                                                                                                                                                                                                                                                                                                                                    {

                                                                                                                                                                                                                                                                                                                                                                                                category: category,

                                                                                                                                                                                                                                                                                                                                                                                                            questionNumber: questionNumber,

                                                                                                                                                                                                                                                                                                                                                                                                                        answer: selectedAnswer,

                                                                                                                                                                                                                                                                                                                                                                                                                                    score: selectedScore,

                                                                                                                                                                                                                                                                                                                                                                                                                                                correct:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                selectedAnswer === "redRoom",

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            completed: true,

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        completedAt: new Date()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    merge: true
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    answerSaved = true;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        nextBtn.disabled = false;


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            statusText.textContent =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "✅ Answer saved successfully!";


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return true;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (error) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.error(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "Error saving Mission 14:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            error
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    statusText.textContent =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "❌ Could not save your answer. Please try again.";


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return false;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // ===============================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // DOOR SELECTION
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // ===============================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                doors.forEach(door => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                door.addEventListener(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "click",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        async () => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (answerLocked) return;


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        selectedAnswer =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    door.dataset.answer;


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            selectedScore =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        scores[selectedAnswer] || 0;


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                answerLocked = true;


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Highlight selected door

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                doors.forEach(item => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (item === door) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            item.classList.add(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "selected"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            item.style.opacity =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "0.5";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Progress animation

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    progressFill.style.width =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "100%";


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        statusText.textContent =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "🤖 Analyzing your decision...";


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Small delay

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await new Promise(resolve =>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setTimeout(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                resolve,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1200
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await saveAnswer();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // ===============================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // CONTINUE BUTTON
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // ===============================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                nextBtn.addEventListener(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "click",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                () => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            !selectedAnswer ||
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    !answerSaved
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        window.location.href =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Mission15.html";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // ===============================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // AUTHENTICATION
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // ===============================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onAuthStateChanged(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                auth,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                async user => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!user) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            window.location.href =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Login.html";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        currentUser = user;


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "Mission 14 user:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            currentUser.uid
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await checkPreviousAnswer();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );