import { auth, db } from "./firebase.js";

import {
    doc,
        setDoc
        } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

        import {
            onAuthStateChanged
            } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";


            // ===============================
            // GET ELEMENTS
            // ===============================

            const memoryBox = document.getElementById("memoryBox");
            const countdown = document.getElementById("countdown");

            const options = document.querySelectorAll(".option");

            const fill = document.querySelector(".fill");
            const text = document.querySelector(".analysis p");

            const nextBtn = document.getElementById("nextBtn");


            // ===============================
            // VARIABLES
            // ===============================

            let currentUser = null;
            let selectedAnswer = "";
            let missionCompleted = false;


            // ===============================
            // CORRECT ANSWER
            // ===============================

            const correctAnswer = "return";


            // ===============================
            // CHECK LOGIN
            // ===============================

            onAuthStateChanged(auth, function (user) {

                if (user) {

                        currentUser = user;

                            } else {

                                    alert("Please login first.");

                                            window.location.href = "Login.html";

                                                }

                                                });


                                                // ===============================
                                                // DISABLE CONTINUE
                                                // ===============================

                                                nextBtn.disabled = true;
                                                nextBtn.style.opacity = "0.5";


                                                // ===============================
                                                // MEMORY TIMER
                                                // ===============================

                                                let timeLeft = 5;

                                                countdown.textContent = timeLeft;


                                                const memoryTimer = setInterval(function () {

                                                    timeLeft--;

                                                        countdown.textContent = timeLeft;


                                                            if (timeLeft <= 0) {

                                                                    clearInterval(memoryTimer);


                                                                            // Hide memory words
                                                                                    memoryBox.style.display = "none";


                                                                                            // Allow answer selection
                                                                                                    options.forEach(function (option) {

                                                                                                                option.style.pointerEvents = "auto";
                                                                                                                            option.style.opacity = "1";

                                                                                                                                    });

                                                                                                                                        }

                                                                                                                                        }, 1000);


                                                                                                                                        // ===============================
                                                                                                                                        // DISABLE OPTIONS DURING MEMORY
                                                                                                                                        // ===============================

                                                                                                                                        options.forEach(function (option) {

                                                                                                                                            option.style.pointerEvents = "none";
                                                                                                                                                option.style.opacity = "0.5";


                                                                                                                                                    option.addEventListener("click", function () {

                                                                                                                                                            // Remove previous selection
                                                                                                                                                                    options.forEach(function (item) {

                                                                                                                                                                                item.classList.remove("active");

                                                                                                                                                                                        });


                                                                                                                                                                                                // Select answer
                                                                                                                                                                                                        this.classList.add("active");


                                                                                                                                                                                                                selectedAnswer =
                                                                                                                                                                                                                            this.textContent.trim();


                                                                                                                                                                                                                                    // ===============================
                                                                                                                                                                                                                                            // START AI ANALYSIS
                                                                                                                                                                                                                                                    // ===============================

                                                                                                                                                                                                                                                            fill.style.width = "0%";

                                                                                                                                                                                                                                                                    text.textContent =
                                                                                                                                                                                                                                                                                "🤖 AI is analysing your memory...";


                                                                                                                                                                                                                                                                                        nextBtn.disabled = true;
                                                                                                                                                                                                                                                                                                nextBtn.style.opacity = "0.5";


                                                                                                                                                                                                                                                                                                        setTimeout(function () {

                                                                                                                                                                                                                                                                                                                    fill.style.width = "100%";

                                                                                                                                                                                                                                                                                                                            }, 100);


                                                                                                                                                                                                                                                                                                                                    // ===============================
                                                                                                                                                                                                                                                                                                                                            // COMPLETE ANALYSIS
                                                                                                                                                                                                                                                                                                                                                    // ===============================

                                                                                                                                                                                                                                                                                                                                                            setTimeout(async function () {

                                                                                                                                                                                                                                                                                                                                                                        const isCorrect =
                                                                                                                                                                                                                                                                                                                                                                                        selectedAnswer === correctAnswer;


                                                                                                                                                                                                                                                                                                                                                                                                    if (isCorrect) {

                                                                                                                                                                                                                                                                                                                                                                                                                    text.textContent =
                                                                                                                                                                                                                                                                                                                                                                                                                                        "✅ Excellent! Memory challenge completed successfully.";

                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    text.textContent =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "⚠ Incorrect. The keyword was \"return\".";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // ===============================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // SAVE TO FIRESTORE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // ===============================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (currentUser) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await setDoc(

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                doc(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            db,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "users",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    currentUser.uid,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "missions",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "mission18"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        missionNumber: 18,

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    answer: selectedAnswer,

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                correct: isCorrect,

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            completed: true,

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        completedAt:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        new Date().toISOString()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        missionCompleted = true;


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            nextBtn.disabled = false;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                nextBtn.style.opacity = "1";


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Mission 18 saved successfully!"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (error) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.error(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Error saving Mission 18:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    error
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            alert(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "Could not save Mission 18. Please try again."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            missionCompleted = false;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        alert("Please login first.");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }, 1500);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // ===============================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // CONTINUE TO MISSION 19
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // ===============================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                nextBtn.addEventListener("click", function () {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (selectedAnswer === "") {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            alert("Please select an option first.");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!missionCompleted) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    alert(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Please wait until your answer is saved."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        window.location.href = "Mission19.html";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });