import { auth, db } from "./firebase.js";

import {
    doc,
        setDoc
        } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

        import {
            onAuthStateChanged
            } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";


            const cards = document.querySelectorAll(".card");
            const fill = document.querySelector(".fill");
            const text = document.querySelector(".analysis p");
            const nextBtn = document.getElementById("nextBtn");

            let selectedAnswer = "";
            let currentUser = null;
            let missionCompleted = false;


            // Check logged-in user
            onAuthStateChanged(auth, function (user) {

                if (user) {

                        currentUser = user;

                            } else {

                                    alert("Please login first.");
                                            window.location.href = "Login.html";

                                                }

                                                });


                                                // Disable Continue initially
                                                nextBtn.disabled = true;
                                                nextBtn.style.opacity = "0.5";


                                                // Answer selection
                                                cards.forEach(function (card) {

                                                    card.addEventListener("click", function () {

                                                            // Remove previous selection
                                                                    cards.forEach(function (item) {
                                                                                item.classList.remove("active");
                                                                                        });


                                                                                                // Highlight selected card
                                                                                                        this.classList.add("active");


                                                                                                                // Get answer
                                                                                                                        selectedAnswer = this.textContent.trim();


                                                                                                                                // Start AI analysis
                                                                                                                                        fill.style.width = "0%";

                                                                                                                                                text.textContent =
                                                                                                                                                            "🤖 AI is analysing your answer...";

                                                                                                                                                                    nextBtn.disabled = true;
                                                                                                                                                                            nextBtn.style.opacity = "0.5";


                                                                                                                                                                                    setTimeout(function () {

                                                                                                                                                                                                fill.style.width = "100%";

                                                                                                                                                                                                        }, 100);


                                                                                                                                                                                                                // Save answer to Firebase
                                                                                                                                                                                                                        setTimeout(async function () {

                                                                                                                                                                                                                                    if (!currentUser) {

                                                                                                                                                                                                                                                    text.textContent =
                                                                                                                                                                                                                                                                        "❌ Please login again.";

                                                                                                                                                                                                                                                                                        return;

                                                                                                                                                                                                                                                                                                    }


                                                                                                                                                                                                                                                                                                                try {

                                                                                                                                                                                                                                                                                                                                await setDoc(
                                                                                                                                                                                                                                                                                                                                                    doc(
                                                                                                                                                                                                                                                                                                                                                                            db,
                                                                                                                                                                                                                                                                                                                                                                                                    "users",
                                                                                                                                                                                                                                                                                                                                                                                                                            currentUser.uid,
                                                                                                                                                                                                                                                                                                                                                                                                                                                    "missions",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "mission12"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            missionNumber: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    answer: selectedAnswer,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            completed: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    completedAt: new Date().toISOString()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        missionCompleted = true;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        text.textContent =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "✅ Answer Recorded Successfully";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            nextBtn.disabled = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            nextBtn.style.opacity = "1";


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Mission 12 saved successfully!"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (error) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.error(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Error saving Mission 12:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    error
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    missionCompleted = false;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    text.textContent =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "❌ Could not save your answer.";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        alert(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Could not save Mission 12. Please try again."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }, 1500);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Continue to Mission 13
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    nextBtn.addEventListener("click", function () {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (selectedAnswer === "") {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                alert("Please select an answer first.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!missionCompleted) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        alert(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "Please wait until your answer is saved."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            window.location.href = "Mission13.html";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });