                                                                                                                                                                                                    import { auth, db } from "./firebase.js";

                                                                                                                                                                                                                      import {
                                                                                                                                                                                                                          doc,
                                                                                                                                                                                                                              setDoc
                                                                                                                                                                                                                              } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

                                                                                                                                                                                                                              import {
                                                                                                                                                                                                                                  onAuthStateChanged
                                                                                                                                                                                                                                  } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";


                                                                                                                                                                                                                                  const options = document.querySelectorAll(".option");
                                                                                                                                                                                                                                  const fill = document.querySelector(".fill");
                                                                                                                                                                                                                                  const text = document.querySelector(".analysis p");
                                                                                                                                                                                                                                  const nextBtn = document.getElementById("nextBtn");

                                                                                                                                                                                                                                  let selectedAnswer = "";
                                                                                                                                                                                                                                  let currentUser = null;
                                                                                                                                                                                                                                  let missionCompleted = false;


                                                                                                                                                                                                                                  // Check logged-in user
                                                                                                                                                                                                                                  onAuthStateChanged(auth, function (user) {

                                                                                                                                                                                                                                      if (user) {

                                                                                                                                                                                                                                              currentUser = user;

                                                                                                                                                                                                                                                  } else {

                                                                                                                                                                                                                                                          alert("Please login first.");
                                                                                                                                                                                                                                                                  window.location.href = "Login.html";

                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                      });


                                                                                                                                                                                                                                                                      // Disable Continue initially
                                                                                                                                                                                                                                                                      nextBtn.disabled = true;
                                                                                                                                                                                                                                                                      nextBtn.style.opacity = "0.5";


                                                                                                                                                                                                                                                                      // Select answer
                                                                                                                                                                                                                                                                      options.forEach(function (option) {

                                                                                                                                                                                                                                                                          option.addEventListener("click", function () {

                                                                                                                                                                                                                                                                                  // Remove previous selection
                                                                                                                                                                                                                                                                                          options.forEach(function (item) {
                                                                                                                                                                                                                                                                                                      item.classList.remove("active");
                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                      // Highlight selected option
                                                                                                                                                                                                                                                                                                                              this.classList.add("active");


                                                                                                                                                                                                                                                                                                                                      const radio = this.querySelector("input");

                                                                                                                                                                                                                                                                                                                                              if (radio) {
                                                                                                                                                                                                                                                                                                                                                          radio.checked = true;
                                                                                                                                                                                                                                                                                                                                                                  }


                                                                                                                                                                                                                                                                                                                                                                          // Get selected answer
                                                                                                                                                                                                                                                                                                                                                                                  selectedAnswer =
                                                                                                                                                                                                                                                                                                                                                                                              this.querySelector("span").textContent.trim();


                                                                                                                                                                                                                                                                                                                                                                                                      // Start AI analysis
                                                                                                                                                                                                                                                                                                                                                                                                              fill.style.width = "0%";

                                                                                                                                                                                                                                                                                                                                                                                                                      text.textContent =
                                                                                                                                                                                                                                                                                                                                                                                                                                  "🤖 AI is analysing your deduction...";

                                                                                                                                                                                                                                                                                                                                                                                                                                          nextBtn.disabled = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                  nextBtn.style.opacity = "0.5";


                                                                                                                                                                                                                                                                                                                                                                                                                                                          setTimeout(function () {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fill.style.width = "100%";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }, 100);


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // Save answer
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              setTimeout(async function () {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (!currentUser) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          text.textContent =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "❌ Please login again.";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      try {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      await setDoc(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          doc(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  db,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "users",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  currentUser.uid,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "missions",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "mission11"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  missionNumber: 11,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          answer: selectedAnswer,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  completed: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          completedAt: new Date().toISOString()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              missionCompleted = true;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              text.textContent =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "✅ Deduction Recorded Successfully";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  nextBtn.disabled = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  nextBtn.style.opacity = "1";


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "Mission 11 saved successfully!"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } catch (error) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.error(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "Error saving Mission 11:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          error
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          missionCompleted = false;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          text.textContent =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "❌ Could not save your deduction.";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              alert(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "Could not save Mission 11. Please try again."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }, 1500);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Continue to Mission 12
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          nextBtn.addEventListener("click", function () {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (selectedAnswer === "") {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      alert("Please select an option first.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!missionCompleted) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              alert(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "Please wait until your deduction is saved."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  window.location.href = "Mission12.html";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });